spring.application.name=Library

# Configuração do H2 Database em memória
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialeto do Hibernate para conversar com o H2
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Manda o Hibernate recriar o banco do zero a cada vez que o teste rodar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true

# (Opcional) Mostra os comandos SQL no console para você debugar se precisar
spring.jpa.show-sql=true